inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'app/controllers/catalog_controller.rb'
    - 'config/initializers/devise.rb'

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/controllers/catalog_controller.rb' # holds a long bl configuration

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /\.rake$/
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# Exclude generated code and specs
Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/models/solr_document.rb'
    - 'app/models/application_record.rb'
    - 'app/models/search_builder.rb'
    - 'app/models/user.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/search_history_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'
    - 'spec/**/*'
