development:
  secret_key_base: wmO7amrufSM4qKNnQR5y70HlDbJVApKbQ9eZH3FWxkKB7X4OPMAqMpJJ3WCExDYVxlaaoqugkie4vB8ZXM7NF0zj6U5IjI5j4QnHTDPNxkEDUKTFcQTL5ASyeFYMWBqd

test:
  secret_key_base: 2qSYCLZKFv48qr6ozrDtZYMtvnuCMnH0Shasu78EVUSqWl3fkf0LbAyHBOmMhA5JgbmehepdGOrvVrErDBfLoxCJcpebW2B4VNNPrdRSdx3Vh8k7eVhkTThuuEFSyBr8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
